config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  resources :photos
  resources :links

  resources :collections do
    resources :photos
    resources :links
  end

  resources :users do
    resources :collections
  end

  root 'collections#index'

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :photos, as: :linkable, dependent: :destroy
  has_many :links, as: :linkable, dependent: :destroy

  accepts_nested_attributes_for :photos, allow_destroy: true
  accepts_nested_attributes_for :links, allow_destroy: true

  validates :title, :description, presence: true

  default_scope { order(created_at: :desc) }
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  before_action :get_parent

  include Set_Owner

  def index
    @collections = Collection.all
  end

  def show
    @parts = (@collection.photos + @collection.links).sort_by{|e| e[:created_at]}.reverse
    @user = User.find_by_id(@collection.patternable_id)

    #meta part
    @title = @collection.title + ' by ' + @user.email
    @ogdescription = @collection.title + ' collection'
    @ogauthor = @user.email
    if @parts.size > 0
      @ogimage = @parts.first.image
    end
  end

  def new
    @collection = @parent.collections.build
  end

  def edit
  end

  def create
    @collection = @parent.collections.build(collection_params)
    redirect_to @collection if @collection.save
  end

  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: 'Collection was successfully updated.' }
        format.json { render :show, status: :ok, location: @collection }
      else
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: 'Collection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def get_parent
      @parent = current_user
    end

    def set_collection
      @collection = Collection.find(params[:id])
    end

    def collection_params
      params.require(:collection).permit(:title, :description, :user_id)
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection.html.erb
<article>
  <% if user_signed_in? && current_user.id == collection.patternable_id %>
      <aside>
        <%= link_to edit_collection_path(collection), class:'button' do %>
            <%= fa_icon 'pencil', text:'edit' %>
        <% end %>
        <%= link_to collection, method: :delete, data: { confirm: 'Are you sure?' }, class:'button' do %>
            <%= fa_icon 'trash' %>
        <% end %>
      </aside>
  <% end %>

  <% @user = User.find_by_id(collection.patternable_id) %>
  <i><%= @user.email %> collection:</i><br/>
  <%= link_to collection do %>
      <h3><%= collection.title %></h3>
  <% end %>

  <section>
    <i><%= collection.description %></i>
  </section>
</article>

app/views/collections/_form.html.erb
<%= form_for(@collection) do |f| %>
  <% if @collection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
      <% @collection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, required:true, autofocus:true, class:'center' %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, required:true, rows:5 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/collections/_part.html.erb
<li>
  <figure>
    <%= image_tag(part.image, width:'200') %>
    <figcaption>
      <h4><%= part.title %></h4>
      <i><%= part.description %></i>
      <% if part.has_attribute?(:url) %>
          <%= link_to 'read more', part.url, target: "_blank" %>
      <% else %>
          <%= link_to 'show me image', part.image(:full), target: "_blank" %>
      <% end %>
    </figcaption>
  </figure>
</li>

app/views/collections/edit.html.erb
<% content_for :header do %>
    <h1>Editing Collection</h1>
<% end %>

<article>
    <%= render 'form' %>
</article>

<%= link_to 'to collection', @collection %>
<%#= link_to 'Back', collections_path %>

app/views/collections/index.html.erb
<p id="notice"><%= notice %></p>

<% if user_signed_in? %>
    <% content_for :nav do %>

    <% end %>
<% end %>

<% content_for :header do %>
    <h1>Collections</h1>
<% end %>

<%= render @collections %>

app/views/collections/new.html.erb
<% content_for :header do %>
    <h1>New Collection</h1>
<% end %>
<article>
    <%= render 'form' %>
</article>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<% content_for :header do %>
    <aside>
      <script type="text/javascript" src="//yastatic.net/share/share.js" charset="utf-8"></script><div class="yashare-auto-init" data-yashareL10n="ru" data-yashareType="link" data-yashareQuickServices="vkontakte,facebook,twitter,odnoklassniki,moimir"></div>
      <br/>
      <% if user_signed_in? && current_user.id == @user.id %>
          <%= link_to edit_collection_path(@collection) do %>
              <%= fa_stacked_icon 'pencil inverse', base:'circle' %>
          <% end %>

      <% end %>
    </aside>

    <i><%= @user.email %> collection:</i>
    <h1><%= @collection.title %></h1>
    <i><%= @collection.description %></i>
<% end %>

<% if user_signed_in? && current_user.id == @user.id %>
    <article>
      <%= link_to new_collection_photo_path(@collection), id:'add_photo' do %>
          <%= fa_stacked_icon 'plus inverse', base:'circle', text:'add photo' %>
      <% end %>
      <%= link_to new_collection_link_path(@collection), id:'add_link' do %>
          <%= fa_stacked_icon 'plus inverse', base:'circle', text:'add link' %>
      <% end %>
    </article>
<% end %>

<article>
  <ul>
    <%= render partial: 'part', collection: @parts %>
  </ul>
</article>