config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  resources :photos
  resources :links

  resources :collections do
    resources :photos
    resources :links
  end

  resources :users do
    resources :collections
  end

  root 'collections#index'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  validates :title, :image, presence: true

  has_attached_file :image, url: "/system/:class/:hash/:style.:extension", hash_secret: "longSecretString", styles: {:thumb=>"200x200>", :full=>"800x800>", :prew=>"600x600>"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :set_collection

  include Set_Owner

  def index
    @photos = Photo.all
  end

  def show
    @user = User.find_by_id(@photo.collection.patternable_id)
  end

  def new
    @photo = Photo.new
  end

  def edit
  end

  def create
    @photo = @collection.photos.build(photo_params)
    flash[:notice] = 'Photo created' if @photo.save
    redirect_to @collection
  end

  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_collection
      @collection = Collection.find_by_id(params[:collection_id])
    end

    def set_photo
      @photo = Photo.find(params[:id])
    end

    def photo_params
      params.require(:photo).permit(:title, :description, :image)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_for([@collection,@photo]) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, required:true, autofocus:true, class:'center' %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 10 %>
  </div>
    <div class="field">
      <%= f.label :image %>
      <%= f.file_field :image, required:true %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<% content_for :header do %>
    <h1>Editing Photo</h1>
<% end %>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Photos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.title %></td>
        <td><%= photo.description %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<% content_for :header do %>
    <h1>New Photo</h1>
<% end %>
<article>
    <%= render 'form' %>
</article>

<%= link_to 'Cancel and back to collections', collections_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<% content_for :header do %>
    <% if user_signed_in? && current_user.id == @user.id %>
        <aside>
          <%= link_to edit_photo_path(@photo) do %>
              <%= fa_icon 'pencil', base:'circle', text:'edit'%>
          <% end %>
        </aside>
    <% end %>
    <h1><%= @photo.title %></h1>
    <i><%= @photo.description %></i>
<% end %>

<article>
  <%= image_tag @photo.illustration(:full) %>
  <hr/>
  <%= link_to 'open original size', @photo.illustration.url %>
  <br/>
  <label>Copy it</label>
  <%= text_field(:photo, :illustration, size: 50) %>
</article>

<article>
  <%= link_to image_tag(@photo.illustration.url(:full)), @photo.illustration.url(:original) %>
</article>
<%= link_to 'Back', photos_path %>