config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  resources :photos
  resources :links

  resources :collections do
    resources :photos
    resources :links
  end

  resources :users do
    resources :collections
  end

  root 'collections#index'

end

app/views/layouts/_meta.html.erb
<title><%= @title || 'Eduson test' %></title>

<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="author" content="<%= @author || 'MS' %>">
<meta name="copyright" lang="ru" content="MS" />
<meta name="document-state" content="Dynamic" />
<meta name="resource-type" content="document" />

<meta name="robots" content="all" />

<meta http-equiv="content-language" content="ru" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

<meta property="og:site_name" content="EdusonTest" />
<meta property="og:title" content="<%= @title || 'Eduson Test' %>" />
<meta property="og:description" content="<%= @ogdescription || 'Wanna work @ Eduson. Test Page' %>" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= image_path(@ogimage) %>" />
<meta property="og:image:type" content="image/jpeg" />
<meta property="og:type" content="article" />

<%= favicon_link_tag 'favicon.png' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= render 'layouts/meta' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav>
  <section>
    <ul>
      <li><%= link_to 'Collections', collections_path %></li>
    </ul>
    <ul>
      <%= yield :nav %>
      <li><%= link_to 'Make collection', new_collection_path %></li>
      <% if user_signed_in? %>
            <li><%= current_user.email %> (<%= current_user.sign_in_count %>)</li>
            <li><%= link_to 'logout', destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to 'login', login_path %></li>
      <% end %>
    </ul>
  </section>
</nav>

<main>
  <header>
    <%= yield :header %>
  </header>
  <%= yield %>
</main>

<footer>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</footer>

<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>